language: go
go:
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.7
  - 1.9.7
  - 1.10.8
  - tip
sudo: false
before_install:
  - ./genconst capstone/bindings/python/capstone
  - ./gensymlink capstone/arch
  - ./genspec capstone/tests
notifications:
  email:
    recipients:
      - travis@ben.iagu.net
